- name: configure frontend server
  become: yes
  hosts: frontend
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enabled nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes